blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/RooVetGit/Roo-Cline/discussions/categories/feature-requests
      about: Share and vote on feature requests for Roo Cline
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=RooVeterinaryInc.roo-cline
      about: Enjoying Roo Cline? Leave a review here!
