title: Roo Code Documentation
description: Documentation for the Roo Code project
remote_theme: just-the-docs/just-the-docs

url: https://docs.roocode.com

aux_links:
  "Roo Code on GitHub":
    - "//github.com/RooVetGit/Roo-Code"

# Enable search
search_enabled: true

# Enable dark mode
color_scheme: dark