name: Discord PR Notifier

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.head_ref != 'changeset-release/main'
    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        with:
          args: |
            ğŸš€ **New Pull Request Opened!**
            ğŸ“ **Title:** ${{ github.event.pull_request.title }}
            ğŸ”— <${{ github.event.pull_request.html_url }}>
            ğŸ‘¤ **Author:** ${{ github.event.pull_request.user.login }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
